CREATE TABLE stockProfile 
(
	SP_PK UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
	SP_Name NVARCHAR(100),
	SP_Symbol NVARCHAR(6)
)

CREATE TABLE dailyResults
(
	DR_PK UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	DR_SP UNIQUEIDENTIFIER,
	DR_High FLOAT,
	DR_Low FLOAT,
	DR_Close FLOAT,
	DR_Date NVARCHAR(30),

	CONSTRAINT FK_stockResults FOREIGN KEY (DR_SP)
	REFERENCES stockProfile(SP_PK)
)